### ISSUE TITLE
Yaourt - clone again instead of pull

### ISSUE THREAD

**Issue by postadelmaga** [Phifo/yaourt#1]
I'm new to Arch/AUR/Yaourt so maybe I'm wrong but I think there is a `bug` in the script:

Even if I set a default dir for temp files, everytime I compile again a package yaourt keep cloning the entire rep.

**Comment by Phifo** [comment]
Sorry but I can't understand your problem. This script just download the package-query and yaourt packages from AUR and install it, I don't know what do you mean when "you compile a package again", can you be more specific? :)
